version: "3.4"
services:
  selenoid:
    image: "aerokube/selenoid:latest"
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      - selenoid
    environment:
      - TZ=Asia/Kolkata

  e2e:
    image: e2e-test
    build: .
    depends_on:
      - selenoid
    links:
      - selenoid
    networks:
      - selenoid
    volumes:
      - "./allure-results:/usr/lib/wdio/allure-results"
      - "./logs:/usr/lib/wdio/logs"

networks:
  selenoid:
    name: selenoid
